name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        numpy-version: [1.15.4, 1.19.4]
        include:
          - python-version: 3.8
            numpy-version: 1.15.4
          - python-version: 3.9
            numpy-version: 1.19.4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils-extra
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install numpy==${{ matrix.numpy-version }} scipy matplotlib>=3 cython>=0.28
    - name: Build package
      run: |
        chmod +x dev/build.sh
        dev/build.sh
    - name: Run tests
      run: |
        chmod +x dev/test.sh
        dev/test.sh
