name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
        django-version: ['2.2', '3.0', '3.1']
        include:
          - python-version: '3.7'
            django-version: '3.0'
            env: docs
          - python-version: '3.7'
            django-version: '3.0'
            env: quality
      allow_failures:
        - python-version: '3.9'
          django-version: '3.1'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests
      env:
        DJANGO: ${{ matrix.django-version }}
        TOXENV: ${{ matrix.env || '' }}
      run: tox
