name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
        include:
          - python-version: 3.8
            TOXENV: py38
          - python-version: 3.9
            TOXENV: py39
          - python-version: 3.10
            TOXENV: py310
          - python-version: 3.11
            TOXENV: py311
          - python-version: 3.11
            TOXENV: flake8
          - python-version: 3.11
            TOXENV: isort
          - python-version: 3.11
            TOXENV: black
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run Tox
      run: tox -e ${{ matrix.TOXENV }}
