name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.9, 3.8, pypy-3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools>=18.5 wheel
        pip install -e . --use-deprecated=legacy-resolver || pip install -e . --use-deprecated=legacy-resolver --no-build-isolation
    - name: Install specific greenlet version
      run: pip install greenlet==1.1.2
    - name: Run tests
      run: python runtests.py
