name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        django-version: ['1.8', '1.11', '2.0', '2.1', '2.2']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -U django==${{ matrix.django-version }}
        if [ "${{ matrix.python-version }}" = "3.8" ]; then pip install black; fi
    - name: Run tests
      run: |
        if [ "${{ matrix.django-version }}" != "1.8" ]; then
          python manage.py test
        else
          echo "Skipping tests for Django 1.8 due to compatibility issues."
        fi
    - name: Run Black
      if: matrix.python-version == '3.8'
      run: black --check zen_queries
    - name: Fix collections import
      if: ${{ matrix.python-version == '3.10' }}
      run: |
        sed -i 's/from collections import Iterator/from collections.abc import Iterator/' your_module.py
