name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        django-version: [21, 22, 30, 31]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage pytest

    - name: Create tox environment
      run: |
        echo "[tox]" > tox.ini
        echo "envlist = py37-django21, py37-django22, py37-django30, py37-django31, py38-django21, py38-django22, py38-django30, py38-django31" >> tox.ini
        echo "[testenv]" >> tox.ini
        echo "deps =" >> tox.ini
        echo "    django21: Django>=2.1,<2.2" >> tox.ini
        echo "    django22: Django>=2.2,<2.3" >> tox.ini
        echo "    django30: Django>=3.0,<3.1" >> tox.ini
        echo "    django31: Django>=3.1,<3.2" >> tox.ini
        echo "    coverage" >> tox.ini
        echo "    pytest" >> tox.ini
        echo "commands = coverage run -m pytest" >> tox.ini

    - name: Run tests
      env:
        TOX_ENV: py${{ matrix.python-version }}-django${{ matrix.django-version }}
      run: tox -r -e $TOX_ENV

    - name: Upload coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v2
