name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox-travis coveralls
    - name: Run tests
      run: tox
    - name: Upload coverage to Coveralls
      if: success()
      run: coveralls

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox-travis sphinx
    - name: Build Docs
      run: |
        set -o pipefail
        tox -e docs | tee build.log
      continue-on-error: true
    - name: Check for Sphinx warnings
      run: |
        if grep -q "WARNING" build.log; then
          echo "Sphinx build produced warnings, failing the job."
          exit 1
        fi
