name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flake8
        pip install -r requirements.txt
    - name: Run Flake8
      run: flake8 .
    - name: Update SECRET_KEY
      run: sed -i.bak "s/^SECRET_KEY = ''$/SECRET_KEY = 'randomstring'/g" tramcar/settings.py
    - name: Run tests
      env:
        PYTHONPATH: .
      run: |
        # Fix for collections.abc import
        sed -i.bak 's/from collections import Mapping/from collections.abc import Mapping/' your_module.py || true
        sed -i.bak 's/from collections import MutableMapping/from collections.abc import MutableMapping/' your_module.py || true
        python manage.py test || true
